console.log('HelloWorld');
console.log(123);
console.log(true);
var greeting = 'Hello';
console.log(greeting);
console.log([1,2,3,4]);
console.log({a:1, b:2});
console.table({a:1, b:2});
console.clear();
console.error('This is a error');
console.warn('This is a warning');
console.time('Hello');
console.log('HelloWorld');
console.log('HelloWorld');
console.log('HelloWorld');
console.log('HelloWorld');
console.log('HelloWorld');
console.log('HelloWorld');
console.log('HelloWorld');
console.log('HelloWorld');
console.timeEnd('Hello');
